name: Terraform VPC Deploy

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "environment/production/**"
      - "modules/**"
      - ".github/workflows/terraform-vpc-deploy.yml"
  push:
    branches: [ "main" ]
    paths:
      - "environment/production/**"
      - "modules/**"
      - ".github/workflows/terraform-vpc-deploy.yml"

permissions:
  contents: read
  id-token: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_CLI_ARGS_apply: "-auto-approve"

jobs:
  vpc:
    name: Apply VPC (production)
    runs-on: ubuntu-latest

    # This is your stack root
    defaults:
      run:
        working-directory: environment/production/vpc/hhc-shared-prd-vpc

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}        # your target project
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}  # your Terraform state bucket
      TF_BACKEND_PREFIX: "state/production/vpc/hhc-shared-prd-vpc"

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP (Service Account JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # optional: nice to have
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Keep backend.tf minimal in repo: terraform { backend "gcs" {} }
      - name: Terraform Init (GCS backend)
        run: |
          terraform init \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="prefix=${TF_BACKEND_PREFIX}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="project_id=${PROJECT_ID}"

      - name: Upload plan on PRs
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: environment/production/vpc/hhc-shared-prd-vpc/terraform.tfplan
        continue-on-error: true

      - name: Terraform Apply (push to main only)
        if: github.event_name == 'push'
        run: terraform apply -var="project_id=${PROJECT_ID}"
