name: Terraform VPC + GKE Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Two roots to run
      matrix:
        workdir:
          - environment/production/vpc/hhc-shared-prd-vpc
          - environment/production/gke

    name: Apply (${{ matrix.workdir }})

    steps:
      - uses: actions/checkout@v4

      - name: Sanity
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Workdir: ${{ matrix.workdir }}"
          echo "PWD before cd:" && pwd

      - name: Authenticate to GCP (Service Account JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Fmt (repo)
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform -chdir="${{ matrix.workdir }}" init -input=false

      - name: Terraform Validate
        run: terraform -chdir="${{ matrix.workdir }}" validate

      - name: Terraform Plan
        run: terraform -chdir="${{ matrix.workdir }}" plan -out=tfplan.out -input=false -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      # Optional: comment this whole step out if you don’t need artifacts
      - name: Upload plan on PRs
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: "tf-plan-${{ matrix.workdir }}"
          path: "${{ matrix.workdir }}/tfplan.out"
        continue-on-error: true

      - name: Terraform Apply (push only)
        if: github.event_name == 'push'
        run: terraform -chdir="${{ matrix.workdir }}" apply -input=false tfplan.out
